import React, { useEffect } from 'react'
import Head from 'next/head'
import Layout from '../components/Layout'
import Logo from '../components/Logo'
import Socials from '../components/Socials'
import { NextPage } from 'next'
import client from '../services'
import PINNED from '../services/PINNED'
import axios from 'axios'

type Props = {
  repos: object
}

const Home: NextPage<Props> = ({ repos }) => {
  useEffect(() => {
    ;(async () => {
      const api = await axios.get(
        'https://api.linkedin.com/v2/people/(id:thomazot)?projection=(geoLocation(geo~,autoGenerated))'
      )
      console.log(api)
    })()
  }, [])
  return (
    <>
      <Head>
        <title>thomazot - Front End Developer</title>
      </Head>
      <Layout>
        <Logo />
        <Socials />
      </Layout>
    </>
  )
}

Home.getInitialProps = async () => {
  const { data } = await client.query({ query: PINNED })
  return { repos: data }
}

export default Home
